[package]
name = "artifex-server"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Artifex server program"

[dependencies]
artifex-engine = { path = "../artifex-engine" }
artifex-rpc = { path = "../artifex-rpc" }
futures = "0.3.29"
tokio = { version = "1.34.0", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["net"] }
tonic = { version = "0.11.0", features = ["tls"] }
tonic-reflection = "0.11.0"
tonic-web = "0.11.0"
clap = { version = "4.4.8", features = ["derive"] }
anyhow = "1.0.75"
toml = "0.8.22"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
