[package]
name = "artifex-rpc"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
prost = "0.12.3"
tonic = "0.10.2"

[build-dependencies]
tonic-build = "0.10.2"
