//
// Copyright (C) 2022 Eric Le Bihan <eric.le.bihan.dev@free.fr>
//
// SPDX-License-Identifier: MIT
//

syntax = "proto3";

package artifex;

// Service to manage a machine
service Artifex {
  // Inspect machine
  rpc Inspect(InspectRequest) returns (InspectReply) {}
  // Execute a command on a machine
  rpc Execute(ExecuteRequest) returns (ExecuteReply) {}
  // Upgrade a the system of a machine
  rpc Upgrade(UpgradeRequest) returns (stream UpgradeReply) {}
  // Upload a file in the cache of a machine.
  rpc Upload(stream UploadRequest) returns (UploadResponse);
}

message InspectRequest {}

// Reply from machine inspection
message InspectReply {
  // The version of the kernel the machine is running on
  string kernel_version = 1;
  // The time since system boot, in seconds.
  uint64 system_uptime = 2;
}

message ExecuteRequest {
  // The command to execute on the machine.
  string command = 1;
}

// Reply from the execution of a command
message ExecuteReply {
  // Standard output
  string stdout = 1;
  // Standard error
  string stderr = 2;
  // Command exit code
  int32 code = 3;
}

message UpgradeRequest {}

// Reply streamed when upgrading the system of a machine
message UpgradeReply {
  enum Status {
    RUNNING = 0;
    SUCCESS = 1;
    FAILURE = 2;
  }
  Status status = 1;
  int32 position = 2;
}

// Request streamed when uploading a file.
message UploadRequest {
  // Payload of the streamed request.
  oneof payload {
    TransferPrologue prologue = 1;
    TransferChunk chunk = 2;
    TransferEpilogue epilogue = 3;
    TransferError error = 4;
  }
}

enum DigestKind {
  BLAKE3 = 0;
}

message Digest {
  DigestKind kind = 1;
  bytes data = 2;
}

// Prologue when transfering a file.
message TransferPrologue {
  // Name of the file being transfered.
  string file_name = 1;
  // Size of the file being transfered.
  uint64 file_size = 2;
}

// Chunk of data when transfering a file.
message TransferChunk {
  // Data from the file being transfered.
  bytes data = 1;
}

// Epilogue when transferring a file.
message TransferEpilogue {
  // Digest of the file transferred.
  Digest digest = 1;
}

// Error when transferring a file.
message TransferError {
  // Reason for the error.
  string reason = 1;
}

// Reply when uploading a file.
message UploadResponse {
  string file_path = 1;
  uint64 file_size = 2;
}
